# Рабочая тетрадь 2

## Петренко Егор, ББСО-01-21

### 1.3.1 Задание

Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.


In [4]:
import numpy as np

lst = []
lst = np.zeros((8, 8))
lst[::2, 1::2] = 1
lst[1::2, ::2] = 1
print(lst)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


### 1.3.2 Задание

Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange.


In [5]:
import numpy as np

lst = np.zeros((5,5))
lst += np.arange(5)
print(lst)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


### 1.3.3 Задание

Создать массив 3x3x3 со случайными значениями.

In [6]:
import numpy as np

lst = np.random.random((3,3,3))

print(lst)

[[[0.07685526 0.08532534 0.05468715]
  [0.8620758  0.54320307 0.02744163]
  [0.90063582 0.01275901 0.12968479]]

 [[0.86051971 0.54743095 0.05496134]
  [0.50904146 0.08706646 0.69042313]
  [0.95418618 0.40345682 0.59826808]]

 [[0.13703607 0.77038582 0.40462494]
  [0.03572071 0.49384818 0.16839338]
  [0.81268729 0.38884946 0.69900316]]]


### 1.3.4 Задание

Создать матрицу с 0 внутри, и 1 на границах.

In [7]:
import numpy as np

lst = np.ones((10, 10))
lst[1:-1,1:-1] = 0

print(lst)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 1.3.5 Задание

Создайте массив и отсортируйте его по убыванию.

In [8]:
import numpy as np

print(np.sort(np.arange(10))[::-1])

[9 8 7 6 5 4 3 2 1 0]


### 1.3.6 Задание

Создайте матрицу, выведите ее форму, размер и размерность.

In [9]:
import numpy as np

lst = np.array([[0, 1, 2, 3], [2, 2, 9, 8]])
print(np.shape(lst), np.size(lst), np.ndim(lst))

(2, 4) 8 2


### 2.3.1 Задание

Найдитн евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.


In [3]:
import pandas as pd

a = pd.Series([1, 2, 3, 4])
b = pd.Series([4, 3, 2, 1])

print(sum((a - b)**2)**0.5)

4.47213595499958


### 2.3.2 Задание

Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [4]:
url = 'https://raw.githubusercontent.com/akmand/datasets/main/airlines.csv'
dataframe = pd.read_csv(url)
dataframe.head(10)

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1
2      AA    2400         LAX       DFW          3    20     165      1
3      AA    2466         SFO       DFW          3    20     195      1
4      AS     108         ANC       SEA          3    30     202      0
5      CO    1094         LAX       IAH          3    30     181      1
6      DL    1768         LAX       MSP          3    30     220      0
7      DL    2722         PHX       DTW          3    30     228      0
8      DL    2606         SFO       MSP          3    35     216      1
9      AA    2538         LAS       ORD          3    40     200      1

### 2.3.3 Задание

Проделайте с получившемся из предыдущего задания фреймом данных
те же действия, что и в примерах 2.2.5-2.2.7.


#### 2.2.5 Пример
Пронализировать характеристики фрейма данных.

In [16]:
print(dataframe.head(3))
print(dataframe.tail(2))
print(dataframe.shape)
print(dataframe.describe())

  Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0      CO     269         SFO       IAH          3    15     205      1
1      US    1558         PHX       CLT          3    15     222      1
2      AA    2400         LAX       DFW          3    20     165      1
       Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
539381      UA      78         HNL       SFO          5  1439     313      1
539382      US    1442         LAX       PHL          5  1439     301      1
(539383, 8)
              Flight      DayOfWeek           Time         Length  \
count  539383.000000  539383.000000  539383.000000  539383.000000   
mean     2427.928630       3.929668     802.728963     132.202007   
std      2067.429837       1.914664     278.045911      70.117016   
min         1.000000       1.000000      10.000000       0.000000   
25%       712.000000       2.000000     565.000000      81.000000   
50%      1809.000000       4.000000     795.000000     

#### 2.2.6 Пример
Выберите индивидуальные данные или срезы фрейма данных.

In [13]:
dataframe.iloc[45:50]

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
45      DL    1276         MSP       ATL          3   320     158      0
46      OO    4651         FAR       MSP          3   320      62      1
47      CO    1585         MFE       IAH          3   325      64      0
48      CO     222         MSY       IAH          3   325      70      0
49      EV    4966         VPS       ATL          3   325      69      0

#### 2.2.7 Пример
Требуется отобрать строки фрейма данных на основе некоторого
условия. Необходимо сформировать новый фрейм данных из пассажиров
первого класса.


In [5]:
dataframe[dataframe['Time'] == 15].head(4) ## Не работает со столбцами, где символы, узнать почему

Airline  Flight AirportFrom AirportTo  DayOfWeek  Time  Length  Delay
0          CO     269         SFO       IAH          3    15     205      1
1          US    1558         PHX       CLT          3    15     222      1
17613      CO     269         SFO       IAH          4    15     205      1
17614      US    1558         PHX       CLT          4    15     222      0

### 3.3.2 Задание

Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.


In [15]:
from sklearn import preprocessing
from sklearn.preprocessing import MinMaxScaler, StandardScaler

dataframe_ = pd.read_csv('https://raw.githubusercontent.com/akmand/datasets/main/iris.csv')
dataframe_[['sepal_length_cm']] = MinMaxScaler().fit_transform(dataframe_[['sepal_length_cm']])
dataframe_[['sepal_width_cm']] = StandardScaler().fit_transform(dataframe_[['sepal_width_cm']])
dataframe_.head(10)

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0         0.222222        1.032057              1.4             0.2  setosa
1         0.166667       -0.124958              1.4             0.2  setosa
2         0.111111        0.337848              1.3             0.2  setosa
3         0.083333        0.106445              1.5             0.2  setosa
4         0.194444        1.263460              1.4             0.2  setosa
5         0.305556        1.957669              1.7             0.4  setosa
6         0.083333        0.800654              1.4             0.3  setosa
7         0.194444        0.800654              1.5             0.2  setosa
8         0.027778       -0.356361              1.4             0.2  setosa
9         0.166667        0.106445              1.5             0.1  setosa